/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://dxtqrw6sn5ffzhssk4hnkrouua.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5tqbsohxbvadraw72eunn6w5ym",
    "aws_cognito_identity_pool_id": "us-east-1:8258b0fd-6b06-444b-bdac-1ca5857d3522",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BYdVjVJk4",
    "aws_user_pools_web_client_id": "6faggiu5gb5mncnfc2ic753s7r",
    "oauth": {
        "domain": "2irlt7c3p6wk-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://2irlt7c3p6wk-staging.auth.us-east-1.amazoncognito.com/",
        "redirectSignOut": "https://2irlt7c3p6wk-staging.auth.us-east-1.amazoncognito.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
